# Generated by Django 5.2 on 2025-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_id',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
    ]
