# Generated by Django 5.2 on 2025-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_message_card_familycommunity_familyinvitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Wallet_Balance',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
