# Generated by Django 5.1.7 on 2025-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_id',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
